[tool.black]
line-length = 79

[tool.isort]
profile = 'black'
line_length = 79
lines_after_imports = 2
combine_as_imports = true

[[tool.mypy.overrides]]
module = 'pynvim'
ignore_missing_imports = true
